AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "former2"
Description: ""
Resources:
  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub "Security group attached to instances to securely connect to ${RDSDBInstance}. Modification could lead to connection loss."
      GroupName: "ec2-rds-1"
      VpcId: "vpc-0a0cddaf04384e4ab"
      SecurityGroupEgress:
        - DestinationSecurityGroupId: !Ref EC2SecurityGroup2
          Description: !Sub "Rule to allow connections to ${RDSDBInstance} from any instances this security group is attached to"
          FromPort: !GetAtt t
          IpProtocol: "tcp"
          ToPort: !GetAtt RDSDBInstance.Endpoint.Port

  EC2SecurityGroup2:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub "Security group attached to ${RDSDBInstance} to allow EC2 instances with specific security groups attached to connect to the database. Modification could lead to connection loss."
      GroupName: "rds-ec2-1"
      VpcId: "vpc-0a0cddaf04384e4ab"
      SecurityGroupIngress:
        - SourceSecurityGroupId: "sg-048536d18a0d3bcb6"
          SourceSecurityGroupOwnerId: !Ref AWS::AccountId
          Description: "Rule to allow connections from EC2 instances with sg-048536d18a0d3bcb6 attached"
          FromPort: !GetAtt RDSDBInstance.Endpoint.Port
          IpProtocol: "tcp"
          ToPort: !GetAtt RDSDBInstance.Endpoint.Port

  RDSDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Created from the RDS Management Console"
      DBSubnetGroupName: "rds-ec2-db-subnet-group-2"
      SubnetIds:
        - "subnet-0776dc82af5fc0f8d"
        - "subnet-0ed35de78bc7dbf31"

  RDSDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: "opus-database"
      AllocatedStorage: 20
      DBInstanceClass: "db.t2.micro"
      Engine: "mysql"
      MasterUsername: "admin"
      MasterUserPassword: "REPLACEME"
      PreferredBackupWindow: "08:05-08:35"
      BackupRetentionPeriod: 7
      AvailabilityZone: !Sub "${AWS::Region}a"
      PreferredMaintenanceWindow: "mon:12:59-mon:13:29"
      MultiAZ: false
      EngineVersion: "8.0.28"
      AutoMinorVersionUpgrade: true
      LicenseModel: "general-public-license"
      PubliclyAccessible: false
      StorageType: "gp2"
      Port: 3306
      StorageEncrypted: false
      CopyTagsToSnapshot: true
      MonitoringInterval: 0
      EnableIAMDatabaseAuthentication: false
      EnablePerformanceInsights: false
      DeletionProtection: false
      DBSubnetGroupName: "rds-ec2-db-subnet-group-2"
      VPCSecurityGroups:
        - !Ref EC2SecurityGroup3
      MaxAllocatedStorage: 200
      DBParameterGroupName: "default.mysql8.0"
      OptionGroupName: "default:mysql-8-0"
      CACertificateIdentifier: "rds-ca-2019"

  EC2SecurityGroup3:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Created by RDS management console"
      GroupName: "db-firewall-sg"
      VpcId: "vpc-0a0cddaf04384e4ab"
      SecurityGroupIngress:
        - CidrIp: "177.157.236.147/32"
          FromPort: 3306
          IpProtocol: "tcp"
          ToPort: 3306
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "-1"
